name: anomaly
channels:
  - conda-forge
  - defaults
dependencies:
- jupyterlab=3.0.*
- python=3.7
- pandas=1.2.*
- pip
- scikit-learn=0.24.*
- pip:
  - influxdb-client==1.18.0
  - tensorflow==2.5.0

