version: '3'
services:
  influxdb:
    image: influxdb:2.0.6
    volumes:
      # Mount for influxdb data directory and configuration
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    ports:
      - "8086:8086"
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=MDS2021
      - DOCKER_INFLUXDB_INIT_PASSWORD=***REMOVED***
      - DOCKER_INFLUXDB_INIT_ORG=UBC
      - DOCKER_INFLUXDB_INIT_BUCKET=MDS2021
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=***REMOVED***

  telegraf:
    image: natewray/telegraf-python:1.18.2
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
      # Mount for telegraf input data
      - ./telegraf/data:/tmp/
    depends_on:
      - influxdb
